### ISSUE TITLE
(Feature Suggestion) Allow script types / flags to be defined in includes

### ISSUE THREAD

**Issue by TehRealSalt** [DavidPH/GDCC#51]
Hi, I came across GDCC looking for an ACS compiler that would fit the needs for a total conversion I'm working on. I noted that specials were defined in the .acs/.h files for GDCC, which was perfect for me since I just want to keep the language to be able to carry across engine familiarity, and just redefine what functions it has.

My only concern is if it'd be possible to add redefining script types/flags (OPEN, ENTER, NET, etc)? I think it's the only thing that I'm worried about. My options without that are:
 - Maintain another version of the tool that just edits the hardcoded strings. I would like to avoid this because whenever the total conversion I'm working on needed to do its own thing, one tool gets made for it ever, and then it annoyingly gets out-of-date.
 - Reuse existing names for different purposes. Don't like this because it'd be a bit misleading. Could probably just use a `#define` to remap to less misleading names for the ACS version, but either way, would be kind of a gross hack.

I think I have a vague idea how to implement it in the ACS version of the compiler, but the C compiler part is a bit beyond me 😅 

Thanks in advance 🙇‍♀️

**Comment by DavidPH** [comment]
I think a language feature that only creates script type/flag aliases would be too redundant with macros. (Especially in the C front where the attribute syntax already incentivizes the use of macros.) However, since both the ACS and C fronts pass as-is strings to the bytecode layer, there could be a linker option to define custom mappings for type strings. Something like, `--bc-zdacs-script-type <string> <int>` and `--bc-zdacs-script-flag`. This would also have the advantage of not restricting you to the existing number of script types/flags. Also, since GDCC supports option files with `@file`, I think this would not be greatly different from having a different `--target-engine` in usage.

I don't want to make any specific promises about how soon I can get around to it, but reminding myself of how the bytecode translation is done makes me think it should be pretty simple once I have the time. Meanwhile, I would say macros are your best option at the moment. That really is the prime syntax-rewording mechanic of either language.

As a side note, I would prefer not to introduce a language feature for defining new script types/flags. Too much design work in both syntax and how to store it in the IR sensibly, for what I think is a pretty obscure feature.

**Comment by TehRealSalt** [comment]
That makes sense, thank you for the speedy response!! 🙏 I appreciate your work on both this + ACSVM, they have been incredibly useful for quick prototyping

**Comment by DavidPH** [comment]
Implemented the new options, including making sure you can use hex for the flag definitions. (I was pretty unhappy with the state of integer parsing in option handling when I saw it.) Let me know if this does what you need. Do be aware that these options can override existing flags/types, but cannot remove them. For example, you can redefine `bluereturn` to map to a different value, but you can't make it unmapped.

**Comment by TehRealSalt** [comment]
Just got around to building, it works perfectly. Thank you so much!!
